apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: example
spec:
  selector:
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
    # - protocol: 'TCP'
    #   post: 443
    #   targetPort: 443
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels:
    group: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
      tier: backend
    # matchExpressions:
    #   - {key: app, operator: In, value: [second-app, first-app]}
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-node
          image: omar0940/kub-first-app:v2
          # - name: ...
          #   image: ...
         
# kubectl apply -f master-deployment.yaml

# to delete the deployment and service not the yaml file 
# kubectl delete -f master-deployment.yaml

# to delete the deployment and service with label
#  kubectl delete deployments,services -l group=example       