apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
    # - protocol: 'TCP'
    #   post: 443
    #   targetPort: 443
  type: LoadBalancer

# kubectl apply -f service.yaml


# to delete the deployment and service not the yaml file 
# kubectl delete -f service.yaml -f deployment.yaml