---
- name: Webserver setup
  hosts: webservers
  become: true
  tasks:
    - name: install httpd
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Start service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

- name: DBserver setup
  hosts:  dbservers
  become: true
  tasks:
    - name: install mariadb
      ansible.builtin.yum:
        name: mariadb-server
        state: present
    - name: Start mariadb service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes