apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
    # - ReadOnlyMany    not working with hostpath
    # - ReadWriteMany   not working with hostpath
  hostPath:
    path: /data
    type: DirectoryOrCreate

