---
# tasks file for post-install
- name: Install ntp agent on centos
  yum:
    name: "{{item}}"
    state: present
  when: ansible_distribution == "CentOS"
  loop:
    - chrony
    - wget
    - git
    - zip
    - unzip
- name: Install ntp agent on ubuntu
  apt:
    name: "{{item}}"
    state: present
    update_cache: true
  when: ansible_distribution == "Ubuntu"
  loop:
    - ntp
    - wget
    - git
    - zip
    - unzip

- name: Start service on CentOS
  service:
    name: chronyd
    state: started
    enabled: true
  when: ansible_distribution == "CentOS"

- name: Start service on Ubuntu
  service:
    name: ntp
    state: started
    enabled: true
  when: ansible_distribution == "Ubuntu"

- name: Banner file
  copy:
    content: '# This server is manged by ansible . No manual changes please'
    dest: /etc/motd

- name: Create a folder
  file:
    path: "{{dir1}}"
    state: directory
- name: Deploy ntp agent conf on centos
  template:
    src: ntpconf_centos.j2
    dest: /etc/chrony.conf
    backup: true
  when: ansible_distribution == "CentOS"
  notify:
    - reStart service on CentOS

- name: Deploy ntp agent conf on Ubuntu
  template:
    src: ntpconf_ubuntu.j2
    dest: /etc/ntp.conf
    backup: true

  when: ansible_distribution == "Ubuntu"
  notify:
    - reStart service on Ubuntu

- name: Dump file
  copy:
    src: myfile.txt
    dest: /tmp/myfile.txt
